<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2014.2.1.284
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Untitled 15 Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'info@kepler.ir',
		'to' => 'info@kepler.ir'
	),
	'fields' => array(
		'Email' => array(
			'type' => 'email',
			'label' => '* نام فروشگاه',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'* نام فروشگاه\' is required.',
				'format' => 'Field \'* نام فروشگاه\' has an invalid email.'
			)
		),
		'custom_U7469' => array(
			'type' => 'string',
			'label' => '* آدرس دقیق فروشگاه',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'* آدرس دقیق فروشگاه\' is required.'
			)
		),
		'custom_U7486' => array(
			'type' => 'string',
			'label' => ' استان',
			'required' => true,
			'errors' => array(
				'required' => 'Field \' استان\' is required.'
			)
		),
		'custom_U7511' => array(
			'type' => 'string',
			'label' => 'شهر',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'شهر\' is required.'
			)
		),
		'custom_U7502' => array(
			'type' => 'string',
			'label' => 'سابقه فعالیت',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'سابقه فعالیت\' is required.'
			)
		),
		'custom_U7519' => array(
			'type' => 'string',
			'label' => '* تلفن',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'* تلفن\' is required.'
			)
		),
		'custom_U7482' => array(
			'type' => 'string',
			'label' => 'فکس',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'فکس\' is required.'
			)
		),
		'custom_U7465' => array(
			'type' => 'string',
			'label' => 'آدرس پست الکترونیکی',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'آدرس پست الکترونیکی\' is required.'
			)
		),
		'custom_U7527' => array(
			'type' => 'checkbox',
			'label' => 'مالک',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'مالک\' is required.'
			)
		),
		'custom_U7477' => array(
			'type' => 'checkbox',
			'label' => 'سرقفلی',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'سرقفلی\' is required.'
			)
		),
		'custom_U7473' => array(
			'type' => 'checkbox',
			'label' => 'مستاجر',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'مستاجر\' is required.'
			)
		),
		'custom_U7507' => array(
			'type' => 'string',
			'label' => '* نام و نام خانوادگی',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'* نام و نام خانوادگی\' is required.'
			)
		),
		'custom_U7515' => array(
			'type' => 'string',
			'label' => '    نام پدر',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'    نام پدر\' is required.'
			)
		),
		'custom_U7523' => array(
			'type' => 'string',
			'label' => 'شماره شناسنامه',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'شماره شناسنامه\' is required.'
			)
		),
		'custom_U7498' => array(
			'type' => 'string',
			'label' => 'تاریخ تولد',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'تاریخ تولد\' is required.'
			)
		),
		'custom_U7490' => array(
			'type' => 'string',
			'label' => '      محل تولد',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'      محل تولد\' is required.'
			)
		),
		'custom_U7532' => array(
			'type' => 'string',
			'label' => 'آیا تا به حال سابقه نمایندگی ارائه خدات شرکت های داخلی و یا خارجی را داشته اید؟ در صورت مثبت بودن پاسخ لطفاً نام ببرید',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'آیا تا به حال سابقه نمایندگی ارائه خدات شرکت های داخلی و یا خارجی را داشته اید؟ در صورت مثبت بودن پاسخ لطفاً نام ببرید\' is required.'
			)
		),
		'custom_U7536' => array(
			'type' => 'string',
			'label' => 'آیا دارای مدرک و یا گواهینامه ای در این زمینه هستید؟ در صورت وجود توضیح دهید',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'آیا دارای مدرک و یا گواهینامه ای در این زمینه هستید؟ در صورت وجود توضیح دهید\' is required.'
			)
		),
		'custom_U7541' => array(
			'type' => 'string',
			'label' => 'در حال حاضر فروشگاه در چه زمینه ای فعالیت دارد؟',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'در حال حاضر فروشگاه در چه زمینه ای فعالیت دارد؟\' is required.'
			)
		)
	)
);

process_form($form);
?>
